# apiVersion: v1
# kind: Service
# metadata:
#   name: sensor-service
# spec:
#   type: {{ .Values.sensorService.service.type }}

#   ports:
#     - port: {{ .Values.sensorService.service.port }}
#       targetPort: {{ .Values.sensorService.service.port }}
#       {{- if and (eq .Values.sensorService.service.type "NodePort") .Values.sensorService.service.nodePort }}
#       nodePort: {{ .Values.sensorService.service.nodePort }}
#       {{- end }}

#   selector:
#     app: sensor-service


apiVersion: v1
kind: Service
metadata:
  name: sensor-service
spec:
  type: NodePort

  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000   
      
    - name: tcp-service
      protocol: TCP
      port: 48321
      targetPort: 48321  
      nodePort: 30000    


  selector:
    app: sensor-service

